### ISSUE TITLE
Graphs not displaying any more in 2.2.3

### ISSUE THREAD

**Issue by Gultak** [RomRider/apexcharts-card#1015]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
Since updating to 2.2.3, my graphs are empty.
Reverting back to 2.2.2 fixes the issue.

This is similar to #945, I opened a new bug as the concole logs are different and the last working version is 2.2.2, not 2.1.2.

**Version of the card**
Version: 2.2.3

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:auto-entities
card:
  type: custom:apexcharts-card
  experimental:
    color_threshold: true
  graph_span: 14d
  section_mode: true
  span:
    end: day
  show:
    last_updated: true
  header:
    show: true
    title: Heating Breakdown
    show_states: true
    colorize_states: true
  yaxis:
    - min: 0
      max: ~9
      decimals: 0
      apex_config:
        tickAmount: 5
  apex_config:
    xaxis:
      tooltip:
        enabled: false
  all_series_config:
    show:
      header_color_threshold: true
    type: column
    group_by:
      func: last
      duration: 1d
    color_threshold:
      - value: 0
        color: green
      - value: 2
        color: yellow
      - value: 8
        color: red
filter:
  template: >-
    {% set ENTITIES =
    states|selectattr('entity_id','search','sensor.*_heating_time') -%}
    {%- for ENTITY in ENTITIES -%}
      {{
        { 'entity': ENTITY.entity_id,
          'name': ENTITY.name|regex_replace(' [hH]eating [tT]ime'),
        } }},
    {%- endfor %}
grid_options:
  columns: full
```

**Screenshots**
<img width="1064" height="289" alt="Image" src="https://github.com/user-attachments/assets/41397ace-f98c-481e-a8ba-7fec2c481aff" />

**Expected behavior**
This is how it looks in 2.2.2 (without the `section_mode: true` tag):
<img width="1066" height="789" alt="Image" src="https://github.com/user-attachments/assets/12ce4504-0f69-4c0b-8340-2d8b80009d47" />

**Desktop (please complete the following information):**
 - Browser: Chrome on Linux
 - Version: 142.0.7444.162

**Additional context**
Error in the Chrome console:
```
apexcharts-card.js?hacstag=331701152223:950
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'entity')
    at apexcharts-card.js?hacstag=331701152223:950:33571
    at c (apexcharts-card.js?hacstag=331701152223:1:1214774)
    at e.value (apexcharts-card.js?hacstag=331701152223:1:1217512)
    at e.value (apexcharts-card.js?hacstag=331701152223:1:1211765)
    at e.value (apexcharts-card.js?hacstag=331701152223:1:1467757)
    at e.create (apexcharts-card.js?hacstag=331701152223:1:905315)
    at apexcharts-card.js?hacstag=331701152223:1:1473569
    at new Promise (<anonymous>)
    at e.value (apexcharts-card.js?hacstag=331701152223:1:1473374)
    at apexcharts-card.js?hacstag=331701152223:1:1423429
```
Code linked:
```javascript
function hc(e, t) {
    return function(o, i, a=e, n=t) {
        var r, s, p;
        const b = Qt(i.seriesIndex, a.series_in_graph, void 0, null == n ? void 0 : n.states[a.series_in_graph[i.seriesIndex].entity]);
        if (!a.series_in_graph[i.seriesIndex].show.in_legend)
            return [];
        if (a.series_in_graph[i.seriesIndex].show.legend_value) {
            let t = Ut.includes(e.chart_type) ? i.w.globals.series[i.seriesIndex].slice(-1)[0] : i.w.globals.series[i.seriesIndex];
            (null === (r = a.series_in_graph[i.seriesIndex]) || void 0 === r ? void 0 : r.invert) && t && (t = -t),
            (null === (s = a.series_in_graph[i.seriesIndex]) || void 0 === s ? void 0 : s.show.as_duration) || (t = ho(t, null == n ? void 0 : n.locale, a.series_in_graph[i.seriesIndex].float_precision));
            const o = "radialBar" === e.chart_type ? "%" : eo(i.seriesIndex, a.series_in_graph, void 0, null == n ? void 0 : n.states[a.series_in_graph[i.seriesIndex].entity]);
            let c = "";
            return c = null == t ? `<strong>${Vt} ${o}</strong>` : (null === (p = a.series_in_graph[i.seriesIndex]) || void 0 === p ? void 0 : p.show.as_duration) ? `<strong>${ro(t, a.series_in_graph[i.seriesIndex].show.as_duration)}</strong>` : `<strong>${t} ${o}</strong>`,
            [b + ":", c]
        }
        return [b]
    }
}
```
I neither have `vehicle-info-card` nor any other of the cards mentioned in #945 and linked issues installed, and searching for `%apexcharts` in my Visual Studio Code integration only yields `apexcharts-card`.

**Comment by FocusDrift** [comment]
I have the same issue

**Comment by bodawui** [comment]
same here

**Comment by flemmingkok** [comment]
Almost the same here, except I have to roll back to 2.1.2 to show my graphs correct. Have done this since  HAOS 10.x - all later versions fails as shown above for me.

Edit - same fix as haja77:
Removed [vehicle-info-card](https://github.com/ngocjohn/vehicle-info-card).
Fixed it.

**Comment by Gultak** [comment]
@flemmingkok : Do you have the same error in the browser console? If not, and if you have to roll back to a different version, please open a separate issue, as then it is most definitely a different issue.

**Comment by rs443** [comment]
Experience the same issue. All charts started looking wierd after updating hass to 2025.11. Was using a year old apexcharts-card version, but the issue persisted after update. Some cards doesn't show at all, some are looks wierd. Not using the vehicle-card mentioned.

**Comment by luigi-pi** [comment]
same issue

**Comment by Gultak** [comment]
@rs443 : Do you get the same errors in the browser console? And does moving back to 2.2.2 fix the problems? If not, please open a separate issue as then yours is not the same as mine.

**Comment by haja77** [comment]
Same here

Edit:
Removed [vehicle-info-card](https://github.com/ngocjohn/vehicle-info-card).
Fixed it.

**Comment by Wunni73** [comment]
same issue

**Comment by jbienz** [comment]
> Same here
> 
> Edit: Removed [vehicle-info-card](https://github.com/ngocjohn/vehicle-info-card). Fixed it.

Confirmed that Vehicle Info Card was the culprit for me too. Note that leaving [Vehicle Status Card](https://github.com/ngocjohn/vehicle-status-card) installed by the same author was still OK.

**Comment by Gultak** [comment]
@haja77 , @Wunni73 , @jbienz , @ilexpl01 : Did you really get the same errors as I posted in your browser console?

Because if not, please remove your posts, **as then they are not the same issue**. The issue I have is **not** fixed by removing `vehicle-info-card` as I never had that installed in the first place. If removing `vehicle-info-card` fixes your issue, you are probably affected by #945, not by this one.

**Comment by supergregg** [comment]
I also have the same issue. Running latest of everything. The companion app also does not render the charts any more, I have to kill it and start again and the chart loads. Browsers need to reload or edit the card to make it display.

**Comment by SirJMD** [comment]
Any update on this? I also have the issue where the charts doesn't load on any device.
