### ISSUE TITLE
max: auto  no longer works, all charts stuck at 10

### ISSUE THREAD

**Issue by LordLinhey** [RomRider/apexcharts-card#733]
max: auto - no longer works, all charts stuck at 10
```
    yaxis:
      - id: Power
        seriesName: Power
        show: true
        min: 0
        **max: auto**
        opposite: false
        reversed: false
```
![image](https://github.com/user-attachments/assets/1a8be5cf-82c2-43d1-a345-4b6ff78b804a)

Restored to V2.04 now max: auto works

**Comment by somerandoname** [comment]
I've noticed a potentially similar issue. For me, only one chart was stuck, and was fixed by either:

- switching the order of the entities
- removing the yaxis entry
- or by setting the show in_chart value for the first entity to true

<details>
  <summary>Config</summary>

```
type: custom:apexcharts-card
graph_span: 3d
span:
  start: day
yaxis:
  - show: true
series:
  - entity: sensor.metheoblue_pollen_grass_level
    show:
      in_chart: false
  - entity: sensor.metheoblue_pollen_forecast
    type: line
    data_generator: |
      return entity.attributes.data_1h.time.map((peak, index) => {
        return [new Date(peak).getTime(), entity.attributes.data_1h.pollen_grass[index]];
      });
```
</details>

<details>
  <summary>Broken chart</summary>

![apexcharts](https://github.com/user-attachments/assets/5169d42c-d5e2-4559-be6f-9d3325a68db6)

</details>

**Comment by jaimezapa** [comment]
I'm experiencing the same issue

**Comment by LordLinhey** [comment]
I am just a bit fed up of the constant updates that break the 3rd party
integrations and fronted enhancements.
I know it's all in the best interest of improvement, but there are just too
many issues, which break everything.
It's just become a constant battle and  a full time to job to  keep it all
working.
Such a shame, but I zm beginning go give up on it all.

**Comment by LordLinhey** [comment]
I have just done a complete new install of Home Assistant on a different machine , as an experimental installation. and I still have the same issue with any version past version 2.0.4.
Nobody seems to have investigated this issue with the max: setting and I cannot find anyway around it that works, despite some suggestions.
Please can someone help as I will never be able to upgrade to any later version.
